# Generated by Django 6.1.1 on 2026-09-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='column',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Left'), (2, 'Middle'), (3, 'Right')], default=1),
        ),
    ]
