# Generated by Django 6.1.1 on 2026-09-16 16:31

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_section_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, help_text='Story text. Leave empty to link straight to the source.'),
        ),
        migrations.AlterField(
            model_name='headline',
            name='url',
            field=models.URLField(help_text='Original article on the source outlet.', max_length=1000),
        ),
    ]
